name: My first workflow
on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the repo
      uses: actions/checkout@v4
    - name: Welcome Message
      run: echo "hello"
    - name: List of files
      run: ls
    - name: read the file
      run: cat README.md
