name: Generate ASCII Art work with shell script
on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the repo
      uses: actions/checkout@v4

    - name: List of repo files
      run: ls -ltra      

    - name: Execute ASCII shell script
      run:  |
        chmod +X ascii-script.sh
        ./ascii-script.sh
