name: Generate ASCII Art work
on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install Cowsay program
      run: sudo apt-get install cowsay -y
      
    - name: Execute cosway CMD
      run:  cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

    - name: upload the dragon.txt file
      uses: actions/upload-artifact@v4
      with:
        name: dragon-text-file
        path: dragon.txt #root path

  test_job_2:
    runs-on: ubuntu-latest
    needs: build_job_1
    steps:
    - name: Download the dragon.txt file
      uses: actions/download-artifact@v4
      with:
        name: dragon-text-file #name of the file to be download

    - name: Test file Exists
      run:  grep -i "dragon" dragon.txt

    - name: List of repo files
      run: ls -ltra

  deploy_job_3:
    runs-on: ubuntu-latest
    needs: test_job_2
    steps:

    - name: Download the dragon.txt file
      uses: actions/download-artifact@v4
      with:
        name: dragon-text-file #name of the file to be download
    
    - name: read the file
      run: cat dragon.txt

    - name: deploy
      run: echo "deploying"