name: Generate ASCII Art work
on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install Cowsay program
      run: sudo apt-get install cowsay -y
      
    - name: Execute cosway CMD
      run:  cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

    - name: sleep for 30 sec
      run:  sleep 30
  test_job_2:
    runs-on: ubuntu-latest
    steps:
    - name: sleep for 10 sec
      run: sleep 10

    - name: Test file Exists
      run:  grep -i "dragon" dragon.txt

    - name: List of repo files
      run: ls -ltra

    - name: read the file
      run: cat README.md
  deploy_job_3:
    runs-on: ubuntu-latest
    steps:
    - name: read the file
      run: cat dragon.txt

    - name: deploy
      run: echo "deploying"